### ISSUE TITLE
AttributeError: 'module' object has no attribute 'GitLab'

### ISSUE THREAD

**Issue by ladrua** [pyapi-gitlab/pyapi-gitlab#149]
Trying to test this library with;

<pre>import gitlab

git = gitlab.GitLab('http://10.0.0.200')
git.login("test@username.qho", "password")</pre>

But only get an error like so:

<pre>
Traceback (most recent call last):
  File "gitlab.py", line 1, in <module>
    import gitlab
  File "/mnt/hgfs/KODE/webserver-scripts/gitlab.py", line 3, in <module>
    git = gitlab.GitLab('http://10.0.0.200')
AttributeError: 'module' object has no attribute 'GitLab'
</pre>

I am using GitLab 7.5.1, and installed the library with <code>pip install pyapi-gitlab</code>

**Comment by ladrua** [comment]
My bad, I named my file the same as the library, that caused the error.
