### ISSUE TITLE
AttributeError: 'Gitlab' object has no attribute 'editproject'

### ISSUE THREAD

**Issue by dj-wasabi** [pyapi-gitlab/pyapi-gitlab#155]
Hi,

I have the following function in my Ansible Module for creating an project with your python module:

```
    def updateProject(self, group_name, arguments):
        project_changed = False
        project_name = arguments['name']
        project_id = self.getProjectId(group_name, project_name)
        project_data = self._gitlab.getproject(project_id=project_id)

        for arg_key, arg_value in arguments.items():
            if project_data[arg_key] != arg_value:
                project_changed = True

        if project_changed:
            if self._module.check_mode:
                self._module.exit_json(changed=True)
            return self._gitlab.editproject(project_id=project_id, **arguments)
        else:
            return False
```

When I execute it, I get the following message:

```
failed: [localhost -> 127.0.0.1] => (item=macaroni) => {"failed": true, "item": "macaroni", "parsed": false}
Traceback (most recent call last):
  File "/Users/wdijkerman/.ansible/tmp/ansible-tmp-1441738292.51-154118668596877/gitlab_project", line 1953, in <module>
    main()
  File "/Users/wdijkerman/.ansible/tmp/ansible-tmp-1441738292.51-154118668596877/gitlab_project", line 340, in main
    if project.createOrUpdateProject(project_exists, group_name, project_name, project_path, description, issues_enabled, merge_requests_enabled, wiki_enabled, snippets_enabled, public, visibility_level):
  File "/Users/wdijkerman/.ansible/tmp/ansible-tmp-1441738292.51-154118668596877/gitlab_project", line 165, in createOrUpdateProject
    return self.updateProject(group_name, arguments)
  File "/Users/wdijkerman/.ansible/tmp/ansible-tmp-1441738292.51-154118668596877/gitlab_project", line 259, in updateProject
    return self._gitlab.editproject(project_id=project_id, default_branch="master", **arguments)
AttributeError: 'Gitlab' object has no attribute 'editproject'
```

According to the document, it should exists:
`editproject(project_id, **kwargs)`

Creating the project works.
Or am I doing something wrong?

Kind regards,
Werner

**Comment by Itxaka** [comment]
Hey,

Looks like the latest version upload to pypi (7.8.4) doesn have that method, its only available on master.

Let me bump the version and cut a new minor release with the new improvements.

**Comment by Itxaka** [comment]
Hi again!

I cut a new release, updated the release notes and pushed it to pypi. A simple pip install -U pyapi-gitlab should net you the latests version with that method included.

Thanks and sorry for the confusion!

**Comment by dj-wasabi** [comment]
Hi,

Many thanks! It is working.
