### ISSUE TITLE
pyapi_gitlab.exceptions.HttpError: 403 Forbidden

### ISSUE THREAD

**Issue by ghost** [pyapi-gitlab/pyapi-gitlab#184]
Hello,

I got this error when I tried to create a group with pyapi-gitlab:

```
Traceback (most recent call last):
  File "./add_project.py", line 189, in <module>
    main()
  File "./add_project.py", line 183, in main
    add_modify_project()
  File "./add_project.py", line 74, in add_modify_project
    if not git.creategroup(group, group):
  File "pyapi_gitlab/__init__.py", line 1072, in creategroup
    raise exceptions.HttpError(msg)
pyapi_gitlab.exceptions.HttpError: 403 Forbidden
```

My Gitlab version is 8.8.2-ce.0

Any idea what caused this error?

Thank you.

Asher256

**Comment by Sudo-Kid** [comment]
If you are still experiencing this issue please provide a code sample so I can better assist you.
