### ISSUE TITLE
gitlab.exceptions.GitlabHttpError: 403: 403 Forbidden

### ISSUE THREAD

**Issue by ricky001** [pyapi-gitlab/pyapi-gitlab#265]
While looping to get all branches of a project, the loop works fine but after sometime i am getting below error. What is main reason for getting the error. How it can be resolved

Traceback (most recent call last):
  File "C:\Users\diljale\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\exceptions.py", line 247, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Users\diljale\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\mixins.py", line 94, in list
    obj = self.gitlab.http_list(path, **kwargs)
  File "C:\Users\diljale\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\__init__.py", line 761, in http_list
    return list(GitlabList(self, url, query_data, **kwargs))
  File "C:\Users\diljale\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\__init__.py", line 853, in __init__
    self._query(url, query_data, **kwargs)
  File "C:\Users\diljale\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\__init__.py", line 858, in _query
    **kwargs)
  File "C:\Users\diljale\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\__init__.py", line 699, in http_request
    response_body=result.content)
gitlab.exceptions.GitlabHttpError: 403: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#34>", line 2, in <module>
    for branch in project.branches.list(all=True):
  File "C:\Users\diljale\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gitlab\exceptions.py", line 249, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body)
gitlab.exceptions.GitlabListError: 403: 403 Forbidden

**Comment by glennie** [comment]
Hello,
I've the same issue when I try loop on repositories.
Here is my simplified code:

```python
import urllib3, gitlab, os
url = os.environ.get('GITLAB_URL')
token = os.environ.get('GITLAB_TOKEN')
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
g = gitlab.Gitlab(url, private_token=token, ssl_verify=False)
projects = g.projects.list(per_page=20)
for p in projects:
    repos = p.repositories.list()
    for r in repos:
        print(r.id)
```
I only get one repo id and, then the script fails with ``gitlab.exceptions.GitlabHttpError: 403: 403 Forbidden``.
May be I'm doing something wrong. So not sure if it is a bug.
Any help or directions will be appreciated.

Many thanks and kind regards,
