### ISSUE TITLE
SSL ERROR

### ISSUE THREAD

**Issue by 5ainews** [pyapi-gitlab/pyapi-gitlab#87]
> import gitlab
> git = gitlab.Gitlab("https://gitlab.xxx.com")  
> git.login("xxx@xxx.com","xxxxx") 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pyapi_gitlab-6.2.3-py2.6.egg/gitlab/**init**.py", line 53, in login
    headers={"connection": "close"})
  File "/usr/lib/python2.6/site-packages/requests-2.3.0-py2.6.egg/requests/api.py", line 88, in post
    return request('post', url, data=data, *_kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.3.0-py2.6.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.3.0-py2.6.egg/requests/sessions.py", line 456, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.3.0-py2.6.egg/requests/sessions.py", line 585, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.6/site-packages/requests-2.3.0-py2.6.egg/requests/sessions.py", line 179, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.6/site-packages/requests-2.3.0-py2.6.egg/requests/sessions.py", line 559, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.3.0-py2.6.egg/requests/adapters.py", line 382, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:492: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by ghost** [comment]
Hi,

I guess you're using a self-signed certificate for your GitLab instance. Try to set the `verify_ssl` to `False` in the GitLab constructor, like:

``` bash
git = gitlab.Gitlab("https://gitlab.xxx.com", verify_ssl=False)
```

Please report, if that will work for you :)

**Comment by 5ainews** [comment]
It's work, thanks

**Comment by sbrinkmeyer** [comment]
looking at your source i see you are using the requests module.  instead of verify_ssl=False, it is also possible to set an environment variable that points to your ca bundle

export REQUESTS_CA_BUNDLE='/some/path/to/cert/self.root.ca.pem'

this resolved it for me so that i could still have ssl verification
